apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wdg5y7lc8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wdg5y7lc8-go 
  name: wdg5y7lc8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wdg5y7lc8-go 
